#ifndef PQPAKE_CONSTANTS_H
#define PQPAKE_CONSTANTS_H

#include "api.h"

#define PQPAKE_CT_SIZE CRYPTO_CIPHERTEXTBYTES  // NEWHOPE_CRYPTO_CIPHERTEXTBYTES
#define PQPAKE_PK_SIZE CRYPTO_PUBLICKEYBYTES  // NEWHOPE_CRYPTO_PUBLICKEYBYTES
#define PQPAKE_SK_SIZE CRYPTO_SECRETKEYBYTES  // NEWHOPE_CRYPTO_SECRETKEYBYTES

#if (CRYPTO_N==512)
#define PQPAKE_SYM_KEY_SIZE 32  // SHA256_DIGEST_LENGTH
#define PQPAKE_ENCODEDPK_SIZE 827
#define PQPAKE_PADBITS PQPAKE_ENCODEDPK_SIZE*8-6609
#elif (CRYPTO_N==1024)
#define PQPAKE_SYM_KEY_SIZE 64  // SHA512_DIGEST_LENGTH
#define PQPAKE_ENCODEDPK_SIZE 1739
#define PQPAKE_PADBITS PQPAKE_ENCODEDPK_SIZE*8-13912
#endif

#if (PQPAKE_ENCODEDPK_SIZE%2==0)
#define PQPAKE_EPK_SIZE PQPAKE_ENCODEDPK_SIZE+CRYPTO_BYTES
#else
#define PQPAKE_EPK_SIZE PQPAKE_ENCODEDPK_SIZE+1+CRYPTO_BYTES
#endif

#define PQPAKE_ECT_SIZE PQPAKE_CT_SIZE
#define PQPAKE_SHARED_SECRET_SIZE CRYPTO_BYTES 

#endif  // PQPAKE_CONSTANTS_H
